//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ContentManagement", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string AccountLogout {
            get {
                return ResourceManager.GetString("AccountLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string AFApprovalFlowTitle {
            get {
                return ResourceManager.GetString("AFApprovalFlowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string AFApprovedBy {
            get {
                return ResourceManager.GetString("AFApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End.
        /// </summary>
        internal static string AFDateEnd {
            get {
                return ResourceManager.GetString("AFDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Start.
        /// </summary>
        internal static string AFDateStart {
            get {
                return ResourceManager.GetString("AFDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        internal static string AFOrderNumber {
            get {
                return ResourceManager.GetString("AFOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string AFSection {
            get {
                return ResourceManager.GetString("AFSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AFStatus {
            get {
                return ResourceManager.GetString("AFStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Duration In Hours.
        /// </summary>
        internal static string AFStatusDurationInHours {
            get {
                return ResourceManager.GetString("AFStatusDurationInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string AFTitle {
            get {
                return ResourceManager.GetString("AFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Flow.
        /// </summary>
        internal static string AFTitleMain {
            get {
                return ResourceManager.GetString("AFTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string AFUser {
            get {
                return ResourceManager.GetString("AFUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ARArticleName {
            get {
                return ResourceManager.GetString("ARArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string ARCreator {
            get {
                return ResourceManager.GetString("ARCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        internal static string ARModifiedBy {
            get {
                return ResourceManager.GetString("ARModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string ARModifiedDate {
            get {
                return ResourceManager.GetString("ARModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ARPageID {
            get {
                return ResourceManager.GetString("ARPageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string ARSection {
            get {
                return ResourceManager.GetString("ARSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager.
        /// </summary>
        internal static string ARSFileManager {
            get {
                return ResourceManager.GetString("ARSFileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string ARSiteID {
            get {
                return ResourceManager.GetString("ARSiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string ARSSelect {
            get {
                return ResourceManager.GetString("ARSSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ARStatus {
            get {
                return ResourceManager.GetString("ARStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Site Articles.
        /// </summary>
        internal static string ARTitle {
            get {
                return ResourceManager.GetString("ARTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/?culture=ar.
        /// </summary>
        internal static string CultureLink {
            get {
                return ResourceManager.GetString("CultureLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FormCancel {
            get {
                return ResourceManager.GetString("FormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        internal static string FormDeleteMsg {
            get {
                return ResourceManager.GetString("FormDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Form.
        /// </summary>
        internal static string FormEditForm {
            get {
                return ResourceManager.GetString("FormEditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string FormUpdate {
            get {
                return ResourceManager.GetString("FormUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GridCancel {
            get {
                return ResourceManager.GetString("GridCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record.
        /// </summary>
        internal static string GridConfirmDelete {
            get {
                return ResourceManager.GetString("GridConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Form.
        /// </summary>
        internal static string GridEditFormCaption {
            get {
                return ResourceManager.GetString("GridEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        internal static string GridGroupPanel {
            get {
                return ResourceManager.GetString("GridGroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string GridNew {
            get {
                return ResourceManager.GetString("GridNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string GridSave {
            get {
                return ResourceManager.GetString("GridSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string HPArticle {
            get {
                return ResourceManager.GetString("HPArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string HPArticleName {
            get {
                return ResourceManager.GetString("HPArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string HPHomePageID {
            get {
                return ResourceManager.GetString("HPHomePageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string HPIsActive {
            get {
                return ResourceManager.GetString("HPIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Full Width.
        /// </summary>
        internal static string HPIsFullWidth {
            get {
                return ResourceManager.GetString("HPIsFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Number.
        /// </summary>
        internal static string HPItemsNumber {
            get {
                return ResourceManager.GetString("HPItemsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Per Page.
        /// </summary>
        internal static string HPItemsPerPage {
            get {
                return ResourceManager.GetString("HPItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string HPLanguage {
            get {
                return ResourceManager.GetString("HPLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleType.
        /// </summary>
        internal static string HPModuleTyper {
            get {
                return ResourceManager.GetString("HPModuleTyper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string HPOrderNumber {
            get {
                return ResourceManager.GetString("HPOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string HPPosition {
            get {
                return ResourceManager.GetString("HPPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string HPSection {
            get {
                return ResourceManager.GetString("HPSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string HPSelect {
            get {
                return ResourceManager.GetString("HPSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string HPSelectArticle {
            get {
                return ResourceManager.GetString("HPSelectArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string HPSite {
            get {
                return ResourceManager.GetString("HPSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string HPStatus {
            get {
                return ResourceManager.GetString("HPStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Home Page.
        /// </summary>
        internal static string HPTitle {
            get {
                return ResourceManager.GetString("HPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string HPTitleName {
            get {
                return ResourceManager.GetString("HPTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        internal static string HRContractTypeName {
            get {
                return ResourceManager.GetString("HRContractTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Contract Types.
        /// </summary>
        internal static string HRContractTypeTitle {
            get {
                return ResourceManager.GetString("HRContractTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Departments.
        /// </summary>
        internal static string HRDepartmentsTitle {
            get {
                return ResourceManager.GetString("HRDepartmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string HREmployeeBirthDate {
            get {
                return ResourceManager.GetString("HREmployeeBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string HREmployeeDepartment {
            get {
                return ResourceManager.GetString("HREmployeeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string HREmployeeEmail {
            get {
                return ResourceManager.GetString("HREmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HREmployeeFullName {
            get {
                return ResourceManager.GetString("HREmployeeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        internal static string HREmployeeHireDate {
            get {
                return ResourceManager.GetString("HREmployeeHireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string HREmployeeName {
            get {
                return ResourceManager.GetString("HREmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        internal static string HREmployeeNationalIDNumber {
            get {
                return ResourceManager.GetString("HREmployeeNationalIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National  ID Type.
        /// </summary>
        internal static string HREmployeeNationalTypeID {
            get {
                return ResourceManager.GetString("HREmployeeNationalTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        internal static string HREmployeeNumber {
            get {
                return ResourceManager.GetString("HREmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string HREmployeeOrganization {
            get {
                return ResourceManager.GetString("HREmployeeOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string HREmployeePassword {
            get {
                return ResourceManager.GetString("HREmployeePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string HREmployeePosition {
            get {
                return ResourceManager.GetString("HREmployeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string HREmployeeTitle {
            get {
                return ResourceManager.GetString("HREmployeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string HREmployeeUserName {
            get {
                return ResourceManager.GetString("HREmployeeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string HRMBirthDate {
            get {
                return ResourceManager.GetString("HRMBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        internal static string HRMCode {
            get {
                return ResourceManager.GetString("HRMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string HRMDepartment {
            get {
                return ResourceManager.GetString("HRMDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string HRMDisplayName {
            get {
                return ResourceManager.GetString("HRMDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string HRMDivision {
            get {
                return ResourceManager.GetString("HRMDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string HRMEmployeeID {
            get {
                return ResourceManager.GetString("HRMEmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string HRMFormalSiteUrl {
            get {
                return ResourceManager.GetString("HRMFormalSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string HRMGender {
            get {
                return ResourceManager.GetString("HRMGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        internal static string HRMHireDate {
            get {
                return ResourceManager.GetString("HRMHireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string HRMImage {
            get {
                return ResourceManager.GetString("HRMImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string HRMMaritalStatus {
            get {
                return ResourceManager.GetString("HRMMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string HRMModifiedDate {
            get {
                return ResourceManager.GetString("HRMModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string HRMOrganization {
            get {
                return ResourceManager.GetString("HRMOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string HRMPosition {
            get {
                return ResourceManager.GetString("HRMPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salaried.
        /// </summary>
        internal static string HRMSalariedFlag {
            get {
                return ResourceManager.GetString("HRMSalariedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Leave Hours.
        /// </summary>
        internal static string HRMSickLeaveHours {
            get {
                return ResourceManager.GetString("HRMSickLeaveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Employees.
        /// </summary>
        internal static string HRMTitle {
            get {
                return ResourceManager.GetString("HRMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string HRMUser {
            get {
                return ResourceManager.GetString("HRMUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Hours.
        /// </summary>
        internal static string HRMVacationHours {
            get {
                return ResourceManager.GetString("HRMVacationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_GeniMaster/styles/main.min.css.
        /// </summary>
        internal static string JareedaStyle {
            get {
                return ResourceManager.GetString("JareedaStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/builder-boxes.min.css.
        /// </summary>
        internal static string JareedaStyleAdmin {
            get {
                return ResourceManager.GetString("JareedaStyleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_GeniMaster/styles/en/bootstrap.min.css.
        /// </summary>
        internal static string JareedaStyleBootstrap {
            get {
                return ResourceManager.GetString("JareedaStyleBootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almnatiq Administration Panel.
        /// </summary>
        internal static string MainSiteTitle {
            get {
                return ResourceManager.GetString("MainSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Email Template.
        /// </summary>
        internal static string ManageEmailTemplates {
            get {
                return ResourceManager.GetString("ManageEmailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string MenuItemManagerIcon {
            get {
                return ResourceManager.GetString("MenuItemManagerIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuItemManagerLanguage {
            get {
                return ResourceManager.GetString("MenuItemManagerLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string MenuItemManagerLanguages {
            get {
                return ResourceManager.GetString("MenuItemManagerLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string MenuItemManagerModified {
            get {
                return ResourceManager.GetString("MenuItemManagerModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string MenuItemManagerName {
            get {
                return ResourceManager.GetString("MenuItemManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string MenuItemManagerOrder {
            get {
                return ResourceManager.GetString("MenuItemManagerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string MenuItemManagerPath {
            get {
                return ResourceManager.GetString("MenuItemManagerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Title.
        /// </summary>
        internal static string MenuManagerEnterTitle {
            get {
                return ResourceManager.GetString("MenuManagerEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string MenuManagerName {
            get {
                return ResourceManager.GetString("MenuManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Manager: Menus.
        /// </summary>
        internal static string MenuManagerTitle {
            get {
                return ResourceManager.GetString("MenuManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Type.
        /// </summary>
        internal static string MenuManagerType {
            get {
                return ResourceManager.GetString("MenuManagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string MIDescription {
            get {
                return ResourceManager.GetString("MIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string MIID {
            get {
                return ResourceManager.GetString("MIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MILanguage {
            get {
                return ResourceManager.GetString("MILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string MILink {
            get {
                return ResourceManager.GetString("MILink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MIName {
            get {
                return ResourceManager.GetString("MIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Path.
        /// </summary>
        internal static string MIPhotoPath {
            get {
                return ResourceManager.GetString("MIPhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string MISite {
            get {
                return ResourceManager.GetString("MISite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Main Images.
        /// </summary>
        internal static string MITitle {
            get {
                return ResourceManager.GetString("MITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        internal static string MMISDisplayOrder {
            get {
                return ResourceManager.GetString("MMISDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Page URL.
        /// </summary>
        internal static string MMISExternalPageURL {
            get {
                return ResourceManager.GetString("MMISExternalPageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string MMISIcon {
            get {
                return ResourceManager.GetString("MMISIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MMISLanguage {
            get {
                return ResourceManager.GetString("MMISLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        internal static string MMISMenuName {
            get {
                return ResourceManager.GetString("MMISMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Position.
        /// </summary>
        internal static string MMISMenuPosition {
            get {
                return ResourceManager.GetString("MMISMenuPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Type.
        /// </summary>
        internal static string MMISMenuType {
            get {
                return ResourceManager.GetString("MMISMenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        internal static string MMISPageName {
            get {
                return ResourceManager.GetString("MMISPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Icon.
        /// </summary>
        internal static string MMISRemoveIcon {
            get {
                return ResourceManager.GetString("MMISRemoveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Name.
        /// </summary>
        internal static string MMISSectionName {
            get {
                return ResourceManager.GetString("MMISSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        internal static string MMISSiteName {
            get {
                return ResourceManager.GetString("MMISSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Page Name.
        /// </summary>
        internal static string MMISSystemPageName {
            get {
                return ResourceManager.GetString("MMISSystemPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MMName {
            get {
                return ResourceManager.GetString("MMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string MMOrder {
            get {
                return ResourceManager.GetString("MMOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Menu.
        /// </summary>
        internal static string MMTitle {
            get {
                return ResourceManager.GetString("MMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string MMTitlePath {
            get {
                return ResourceManager.GetString("MMTitlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments Manager.
        /// </summary>
        internal static string MSComments {
            get {
                return ResourceManager.GetString("MSComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string MSPCreator {
            get {
                return ResourceManager.GetString("MSPCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string MSPId {
            get {
                return ResourceManager.GetString("MSPId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string MSPMainPage {
            get {
                return ResourceManager.GetString("MSPMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string MSPModifiedDate {
            get {
                return ResourceManager.GetString("MSPModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MSPName {
            get {
                return ResourceManager.GetString("MSPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Url.
        /// </summary>
        internal static string MSPrivateURL {
            get {
                return ResourceManager.GetString("MSPrivateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string MSPSection {
            get {
                return ResourceManager.GetString("MSPSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Access.
        /// </summary>
        internal static string MSPSecurityAccess {
            get {
                return ResourceManager.GetString("MSPSecurityAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string MSPSite {
            get {
                return ResourceManager.GetString("MSPSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string MSPStatus {
            get {
                return ResourceManager.GetString("MSPStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Site Pages.
        /// </summary>
        internal static string MSPTitle {
            get {
                return ResourceManager.GetString("MSPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS.
        /// </summary>
        internal static string MSRSS {
            get {
                return ResourceManager.GetString("MSRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string MSSite {
            get {
                return ResourceManager.GetString("MSSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string MSSourceName {
            get {
                return ResourceManager.GetString("MSSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string MSTitle {
            get {
                return ResourceManager.GetString("MSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string MUCreatedDate {
            get {
                return ResourceManager.GetString("MUCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string MUDescription {
            get {
                return ResourceManager.GetString("MUDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string MUImage {
            get {
                return ResourceManager.GetString("MUImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string MUName {
            get {
                return ResourceManager.GetString("MUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string MUPublishDate {
            get {
                return ResourceManager.GetString("MUPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Multimedia.
        /// </summary>
        internal static string MUTitle {
            get {
                return ResourceManager.GetString("MUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MUType {
            get {
                return ResourceManager.GetString("MUType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Url.
        /// </summary>
        internal static string MUVideoUrl {
            get {
                return ResourceManager.GetString("MUVideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email Template.
        /// </summary>
        internal static string NewEmailTemplate {
            get {
                return ResourceManager.GetString("NewEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Title.
        /// </summary>
        internal static string PMSAddTitle {
            get {
                return ResourceManager.GetString("PMSAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string PMSAlias {
            get {
                return ResourceManager.GetString("PMSAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string PMSCategory {
            get {
                return ResourceManager.GetString("PMSCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Main Page.
        /// </summary>
        internal static string PMSIsMain {
            get {
                return ResourceManager.GetString("PMSIsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string PMSLanguage {
            get {
                return ResourceManager.GetString("PMSLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string PMSSection {
            get {
                return ResourceManager.GetString("PMSSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Access.
        /// </summary>
        internal static string PMSSecurityAccess {
            get {
                return ResourceManager.GetString("PMSSecurityAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string PMSSite {
            get {
                return ResourceManager.GetString("PMSSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PMSState {
            get {
                return ResourceManager.GetString("PMSState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string RTSignOut {
            get {
                return ResourceManager.GetString("RTSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Title.
        /// </summary>
        internal static string SAAddTitle {
            get {
                return ResourceManager.GetString("SAAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Content.
        /// </summary>
        internal static string SAArticleContent {
            get {
                return ResourceManager.GetString("SAArticleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Title.
        /// </summary>
        internal static string SAArticleShortTitle {
            get {
                return ResourceManager.GetString("SAArticleShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title.
        /// </summary>
        internal static string SAArticleSubTitle {
            get {
                return ResourceManager.GetString("SAArticleSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SAArticleTitle {
            get {
                return ResourceManager.GetString("SAArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Type.
        /// </summary>
        internal static string SAArticleType {
            get {
                return ResourceManager.GetString("SAArticleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string SAAuthor {
            get {
                return ResourceManager.GetString("SAAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string SACategories {
            get {
                return ResourceManager.GetString("SACategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Type.
        /// </summary>
        internal static string SACommentType {
            get {
                return ResourceManager.GetString("SACommentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SADescription {
            get {
                return ResourceManager.GetString("SADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Slider.
        /// </summary>
        internal static string SAInSlider {
            get {
                return ResourceManager.GetString("SAInSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Slider Order.
        /// </summary>
        internal static string SAInSliderOrder {
            get {
                return ResourceManager.GetString("SAInSliderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SALanguage {
            get {
                return ResourceManager.GetString("SALanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string SAMInfoAlias {
            get {
                return ResourceManager.GetString("SAMInfoAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SAMInfoAuthor {
            get {
                return ResourceManager.GetString("SAMInfoAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string SAMInfoImage {
            get {
                return ResourceManager.GetString("SAMInfoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish End.
        /// </summary>
        internal static string SAMInfoPublishEnd {
            get {
                return ResourceManager.GetString("SAMInfoPublishEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Start.
        /// </summary>
        internal static string SAMInfoPublishStart {
            get {
                return ResourceManager.GetString("SAMInfoPublishStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        internal static string SAMoreInfo {
            get {
                return ResourceManager.GetString("SAMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string SAMSources {
            get {
                return ResourceManager.GetString("SAMSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string SAPerson {
            get {
                return ResourceManager.GetString("SAPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string SASection {
            get {
                return ResourceManager.GetString("SASection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Title.
        /// </summary>
        internal static string SAShortTitle {
            get {
                return ResourceManager.GetString("SAShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string SASite {
            get {
                return ResourceManager.GetString("SASite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string SAState {
            get {
                return ResourceManager.GetString("SAState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Title.
        /// </summary>
        internal static string SASubTitle {
            get {
                return ResourceManager.GetString("SASubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Article.
        /// </summary>
        internal static string SATitle {
            get {
                return ResourceManager.GetString("SATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        internal static string SaveandClose {
            get {
                return ResourceManager.GetString("SaveandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; New.
        /// </summary>
        internal static string SaveandNew {
            get {
                return ResourceManager.GetString("SaveandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Email Template.
        /// </summary>
        internal static string SaveEmailTemplate {
            get {
                return ResourceManager.GetString("SaveEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        internal static string SBBlocks {
            get {
                return ResourceManager.GetString("SBBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string SBLayout {
            get {
                return ResourceManager.GetString("SBLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Water Mark.
        /// </summary>
        internal static string SMApplyWaterMark {
            get {
                return ResourceManager.GetString("SMApplyWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string SSAlias {
            get {
                return ResourceManager.GetString("SSAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string SSId {
            get {
                return ResourceManager.GetString("SSId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string SSModifiedDate {
            get {
                return ResourceManager.GetString("SSModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SSName {
            get {
                return ResourceManager.GetString("SSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string SSPerson {
            get {
                return ResourceManager.GetString("SSPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string SSSection {
            get {
                return ResourceManager.GetString("SSSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Parent.
        /// </summary>
        internal static string SSSectionParent {
            get {
                return ResourceManager.GetString("SSSectionParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SSSectionStatus {
            get {
                return ResourceManager.GetString("SSSectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Access.
        /// </summary>
        internal static string SSSecurityAccess {
            get {
                return ResourceManager.GetString("SSSecurityAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string SSSite {
            get {
                return ResourceManager.GetString("SSSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Site Sections.
        /// </summary>
        internal static string SSTitle {
            get {
                return ResourceManager.GetString("SSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        internal static string TBExcel {
            get {
                return ResourceManager.GetString("TBExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string TBNew {
            get {
                return ResourceManager.GetString("TBNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string TBPDF {
            get {
                return ResourceManager.GetString("TBPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string TBWord {
            get {
                return ResourceManager.GetString("TBWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string WBPosition {
            get {
                return ResourceManager.GetString("WBPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string WBSection {
            get {
                return ResourceManager.GetString("WBSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string WBSite {
            get {
                return ResourceManager.GetString("WBSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections Builder.
        /// </summary>
        internal static string WBTitle {
            get {
                return ResourceManager.GetString("WBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string WBType {
            get {
                return ResourceManager.GetString("WBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string WILastArticleModifiedHour {
            get {
                return ResourceManager.GetString("WILastArticleModifiedHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string WILastArticleModifiedItemTitle {
            get {
                return ResourceManager.GetString("WILastArticleModifiedItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string WILastArticleModifiedMinute {
            get {
                return ResourceManager.GetString("WILastArticleModifiedMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last modified from.
        /// </summary>
        internal static string WILastArticleModifiedTitle {
            get {
                return ResourceManager.GetString("WILastArticleModifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Read Today.
        /// </summary>
        internal static string WITopArticleTitle {
            get {
                return ResourceManager.GetString("WITopArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string WITotalArticlesTitle {
            get {
                return ResourceManager.GetString("WITotalArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles Today.
        /// </summary>
        internal static string WITotalArticlesTitleToday {
            get {
                return ResourceManager.GetString("WITotalArticlesTitleToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string WITotalSectionsTitle {
            get {
                return ResourceManager.GetString("WITotalSectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string WITotalVisitsTitle {
            get {
                return ResourceManager.GetString("WITotalVisitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits Today.
        /// </summary>
        internal static string WITotalVisitsTodayTitle {
            get {
                return ResourceManager.GetString("WITotalVisitsTodayTitle", resourceCulture);
            }
        }
    }
}
